flowchart LR
    subgraph Client["Bloc Client"]
        Vista[/"Vista (Input: Nom)"/]
        DaoClient["DaoClient (getUserName)"]
        
        Vista <--> DaoClient
    end

    DaoClient -- "HTTP Request" --> WebService

    subgraph Server["Bloc Servidor"]
        WebService["WebService (getUserByName)"]
        Dao["Dao (getUserByName)"]
        DataStore["Llista d'Usuaris"]
        
        WebService <--> Dao
        Dao <--> DataStore
    end

    WebService -- "HTTP Response" --> DaoClient